using System.Text;

namespace Dualtooth.Core;

/// <summary>Generates the bash script that installs Windows' pairing keys into BlueZ on Linux.</summary>
public static class ScriptGenerator
{
    const string Delimiter = "DUALTOOTH_INFO_EOF";

    public static string Generate(BtAddress adapter, IEnumerable<PairedDevice> devices, DateTime generatedAt)
    {
        var list = devices.ToList();
        if (list.Count == 0) throw new ArgumentException("Select at least one device.", nameof(devices));

        var sb = new StringBuilder();
        sb.Append($$"""
            #!/bin/bash
            # Generated by Dualtooth on {{generatedAt:yyyy-MM-dd HH:mm}}.
            # Installs this PC's Windows Bluetooth pairings into Linux (BlueZ), so these devices
            # work in both operating systems without pairing again.
            #
            # Usage:   sudo bash dualtooth-apply.sh
            #
            # This file contains Bluetooth pairing keys. Delete it once you're done.
            set -euo pipefail

            ADAPTER="{{adapter}}"
            BTDIR="/var/lib/bluetooth/$ADAPTER"

            if [ "$(id -u)" -ne 0 ]; then
              echo "Please run with sudo:  sudo bash $0"; exit 1
            fi

            if [ ! -d "$BTDIR" ]; then
              echo "Bluetooth adapter $ADAPTER was not found in /var/lib/bluetooth."
              echo "Adapters Linux knows about:"; ls /var/lib/bluetooth 2>/dev/null || echo "  (none)"
              echo "Make sure Bluetooth is turned on in Linux, then try again. Nothing was changed."
              exit 1
            fi

            write_device() {  # $1 = device address, $2 = display name; info file contents on stdin
              local file="$BTDIR/$1/info"
              mkdir -p "$BTDIR/$1"
              if [ -f "$file" ]; then cp "$file" "$file.bak"; fi
              cat > "$file"
              chmod 600 "$file"
              echo "Installed $2 ($1)"
            }

            systemctl stop bluetooth 2>/dev/null || service bluetooth stop 2>/dev/null || true


            """.Replace("\r\n", "\n"));

        foreach (var device in list)
        {
            var name = BlueZInfo.SanitizeName(device.Name).Replace("'", "'\\''");
            sb.Append($"write_device {device.Address} '{name}' <<'{Delimiter}'\n");
            sb.Append(BlueZInfo.Build(device));
            sb.Append($"{Delimiter}\n\n");
        }

        sb.Append("""
            # Power the adapter on at boot so Bluetooth keyboards work at the login screen.
            if [ -f /etc/bluetooth/main.conf ]; then
              if grep -qE '^#?\s*AutoEnable' /etc/bluetooth/main.conf; then
                sed -i -E 's/^#?\s*AutoEnable.*/AutoEnable=true/' /etc/bluetooth/main.conf
              else
                sed -i '/^\[Policy\]/a AutoEnable=true' /etc/bluetooth/main.conf
              fi
            fi

            systemctl start bluetooth 2>/dev/null || service bluetooth start 2>/dev/null || true
            echo
            echo "Done. Turn each device off and on again; it should connect within a few seconds."
            echo "Don't pair these devices again in Windows or Linux, or the pairing will split again."

            """.Replace("\r\n", "\n"));

        return sb.ToString();
    }
}
